name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AI PR Code Reviewer
        uses: Sin317/ai-pr-reviewer@1.0.1
        with:
          github_token: ${{ secrets.GH_PAT }}
        env:
          # Pastikan nama environment variable ini sesuai
          # dengan yang diminta oleh dokumentasi script pr_tool.py
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          MODEL: "claude-3-5-sonnet"
